### PR TITLE
Feature/build using published artifacts

### PR DESCRIPTION
**Pull request by bwehrle**
* Remove local build of dependencies; this can cause unstable builds
* Add jcenter and nexus to maven settings file
* Rename of maven settings files to follow convention
* Minor fix to pom to remove "snapshots" element from snapshot repository entry

### CODE REVIEW

**Comment by d-led** [comment]
@VaughnVernon regarding the "platform" and your way of building the whole platform, you might want to take the change from local dependency to the remote one into account. I think, this is a good move that'll allow controlled step-by-step evolution of the platform dependencies.

**Comment by bwehrle** [comment]
snapshots is now merged into master.  I'd appreciate feedback before making a new PR to master.  I don't know if you've considered the alternatives or need to discuss this approach more, but this is how I see most projects being built.

**Comment by d-led** [comment]
Looks ok to me

**Comment by d-led** [comment]
Would you like to rebase/update from master to see if the build is ok?

**Comment by d-led** [comment]
I pressed merge, but didn't realize, it's for the old snapshots branch.
This commit can't work on master without conflicts. @bwehrle would you mind reopening it for master with the conflicts solved?

**Comment by d-led** [comment]
see #30.

**Comment by bwehrle** [comment]
Hi,
Sorry for the late reply, I've been doing Christmas hanging out.   Thanks for making the new PR and merging.

Here is how I see most projects working:
1.  All builds are based on published artifacts
2.  When you want to test changes locally, you can manually update the down-stream projects dependencies to use the SNAPSHOT version, which you've 'installed' locally with Maven.
3.  It seems its a  best practice to publish a BOM with all the artifact versions- this could be inside the platform project.  This could easily be changed manually instead of the downlevel projects to inject the changes, which reduces the frustration factor.
4.  Once the changes are blessed, the  BOM can be updated to point to the latest versions, and the downstream project updated to pick up the latest BOM from the platform project.
https://github.com/resteasy/Resteasy/blob/master/resteasy-bom/pom.xml

There are a few things to change, as you point out,
* The SNAPSHOT text needing to be replaced on build
* It'd be nice to have feature branch snapshots for improving collaboration

The cons are that:
* You need to wait for things to be published before integrating them down-stream
* Higher touch and there is little automation to propagate changes automagically
The pros are that:
* A broken build will not break other projects, therefore the process will scale to more contributors
* The local build is reproducible and mirrors the remote build
* No custom gradle scripts to update versions, all code that gets checked out builds as-is

Maybe you the the existing process better?  Maybe we can try this out on actors and see how it goes?
Regards,
Brian

**Pull request merged**
